import { useState } from "react";
import type { FormEvent } from "react";
import { Clock3, Mail, MapPin, Phone, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
export function ContactSection(){const [sent,setSent]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true);toast({title:"Сообщение отправлено",description:"Ответим вам в течение 15 минут."});};return <section id="contacts" className="py-24"><div className="section-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-3">Мы рядом</p><h2 className="mb-6 text-4xl sm:text-5xl">Есть вопрос?<br/><span className="text-primary">Давайте обсудим</span></h2><p className="mb-8 max-w-md leading-7 text-muted-foreground">Оставьте сообщение, и наш специалист свяжется с вами.</p><div className="space-y-5"><a href="tel:+74951234567" className="flex items-center gap-4"><Phone className="text-primary"/><span><small className="block text-xs text-muted-foreground">Телефон</small><strong>+7 (495) 123-45-67</strong></span></a><a href="mailto:hello@teplofix.ru" className="flex items-center gap-4"><Mail className="text-primary"/><span><small className="block text-xs text-muted-foreground">Почта</small><strong>hello@teplofix.ru</strong></span></a><div className="flex items-center gap-4"><MapPin className="text-primary"/><span><small className="block text-xs text-muted-foreground">Зона выезда</small><strong>Москва и Московская область</strong></span></div><div className="flex items-center gap-4"><Clock3 className="text-primary"/><span><small className="block text-xs text-muted-foreground">Режим работы</small><strong>Ежедневно, 8:00–22:00</strong></span></div></div></div><Card className="p-6 shadow-lg sm:p-8">{sent?<div className="flex min-h-[330px] flex-col items-center justify-center text-center"><Send className="mb-5 text-primary" size={45}/><h3 className="mb-2 text-2xl">Мы получили ваше сообщение</h3><p className="text-sm text-muted-foreground">Скоро свяжемся с вами.</p></div>:<form onSubmit={submit} className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><div><Label className="mb-2 block">Имя</Label><Input required placeholder="Ваше имя"/></div><div><Label className="mb-2 block">Телефон</Label><Input required type="tel" placeholder="+7 (___) ___-__-__"/></div></div><div><Label className="mb-2 block">Электронная почта</Label><Input required type="email" placeholder="you@example.com"/></div><div><Label className="mb-2 block">Сообщение</Label><Textarea required minLength={10} className="min-h-[140px]" placeholder="Расскажите, чем можем помочь"/></div><Button type="submit" size="lg" className="h-12 rounded-xl"><Send size={17}/> Отправить сообщение</Button></form>}</Card></div></section>;}
