import { useState } from "react";
import type { FormEvent } from "react";
import { MessageSquarePlus, Star } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
import { testimonials } from "@/data/siteData";
export function ReviewsSection(){ const [open,setOpen]=useState(false); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setOpen(false);toast({title:"Спасибо за отзыв",description:"Мы проверим его и скоро опубликуем."});}; return <section id="reviews" className="bg-white py-24"><div className="section-shell"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow mb-3">Нам доверяют соседи</p><h2 className="text-4xl sm:text-5xl">Что говорят<br/><span className="text-primary">наши клиенты</span></h2></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl"><MessageSquarePlus size={17}/> Оставить отзыв</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Поделитесь впечатлением</DialogTitle></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid gap-2"><Label>Ваше имя</Label><Input required placeholder="Как к вам обращаться"/></div><div className="grid gap-2"><Label>Город</Label><Input required placeholder="Москва"/></div><div className="grid gap-2"><Label>Оценка сервиса</Label><Select defaultValue="5"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[5,4,3,2,1].map(v=><SelectItem key={v} value={String(v)}>{v} из 5</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Ваш отзыв</Label><Textarea required minLength={10} placeholder="Расскажите о работе мастера"/></div><Button type="submit">Опубликовать отзыв</Button></form></DialogContent></Dialog></div><div className="grid gap-5 lg:grid-cols-3">{testimonials.map(([name,city,text,image])=><Card key={name} className="border-border/70 p-6 shadow-none"><div className="mb-5 flex gap-1 text-[#f5a623]">{[1,2,3,4,5].map(i=><Star key={i} size={15} fill="currentColor"/>)}</div><p className="mb-7 min-h-[105px] text-sm leading-7 text-foreground/80">“{text}”</p><div className="flex items-center gap-3"><Avatar><AvatarImage src={image} alt={name}/><AvatarFallback>{name.slice(0,1)}</AvatarFallback></Avatar><div><strong className="block text-sm">{name}</strong><span className="text-xs text-muted-foreground">{city}</span></div></div></Card>)}</div></div></section>; }
